export const projects = [
    {
      slug: 'ggrc-site',
      title: 'GGRC Crime Data Dashboard',
      description: 'A public crime reporting tool built with React, Tailwind, and Next.js.',
      image: '/images/ggrc-thumbnail.png',
      stack: ['Next.js', 'Tailwind', 'Framer Motion'],
      github: 'https://github.com/yourname/ggrc-site',
      live: 'https://ggrc-site.vercel.app',
      content: `A deep dive into how I built the GGRC site for crime data transparency...`,
    },
    {
      slug: 'jcodestudiosite',
      title: 'Original Portfolio Website',
      description: 'My first personal site — focused on clean design and accessible layout.',
      image: '/images/portfolio-v1.png',
      stack: ['React', 'CSS Modules'],
      github: 'https://github.com/jkarstrom/jCodeStudioSite',
      live: 'https://jcode-v1.netlify.app',
      content: `This was the first iteration of my personal website...`,
    },
    {
      slug: 'portfolio-v1',
      title: 'Original Portfolio Website',
      description: 'My first personal site — focused on clean design and accessible layout.',
      image: '/images/portfolio-v1.png',
      stack: ['React', 'CSS Modules'],
      github: 'https://github.com/jkarstrom/jCodeStudioSite',
      live: 'https://jcode-v1.netlify.app',
      content: `This was the first iteration of my personal website...`,
    },
  ];